AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Severity: fatal

#
# Disabled Cops
#
Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - '/spec/'

Style/DotPosition:
  EnforcedStyle: trailing

Metrics/MethodLength:
  Max: 20
